apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tensor-ingress
spec:
  defaultBackend:
    service:
      name: tensor-svc
      port:
        number: 81
  rules:
  - host: "nginx.tensor.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tensor-svc
            port:
              number: 80
