apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensor
  labels:
    app: tensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensor
  template:
    metadata:
      labels:
        app: tensor
    spec:
      containers:
      - name: nginx-tensor
        image: xeladock/mysql_dns:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: DATABASE_DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: db-dn
              key: db.string
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: empty-volume
            mountPath: /usr/share/nginx/html
      - name: nginx-tensor2
        image: xeladock/nginx2:latest
        ports:
        - containerPort: 81
          protocol: TCP
        volumeMounts:
          - name: empty-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: empty-volume
          emptyDir:
            sizeLimit: 100m
