apiVersion: v1
kind: Service
metadata:
  name: tensor-svc
  labels:
    app: tensor
spec:
  type: ClusterIP
  ports:
    - name: http1  
      port: 80
      protocol: TCP
      targetPort: 80
    - name: http2
      port: 81 
      protocol: TCP
      targetPort: 81
  selector:
    app: tensor
